name: fakedata-example
version: 0.1.0.0
github: "luvemil/fakedata-example"
license: BSD3
author: "Marco Tarantino"
maintainer: "taran.marco@protonmail.com"
copyright: "2021 Marco Tarantino"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/luvemil/fakedata-example#readme>

dependencies:
  - base >= 4.7 && < 5
  - mtl
  - bytestring
  - text
  - time
  - containers
  - lens
  - generic-lens
  - directory
  - unordered-containers
  - uuid
  - fakedata
  - optparse-generic
  - aeson
  - servant-server
  - wai
  - warp
  - fakedata
  - text
  - wai-cors
  - transformers


ghc-options:
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wcompat
  - -Widentities
  - -Wredundant-constraints
  - -fhide-source-paths
  - -Wpartial-fields

default-extensions:
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DeriveGeneric
  - DerivingStrategies
  - DerivingVia
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - OverloadedStrings
  - OverloadedLabels
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TypeApplications
  - TypeFamilies
  - TypeOperators
library:
  source-dirs: src

executables:
  fakedata-example-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - fakedata-example

tests:
  fakedata-example-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - fakedata-example
